### ISSUE TITLE
'update employee' dialog with backend call

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw-forge/devon4flutter-non-bloc-arch#11]
**Description**
As a user I would like to have a dialog where I can change entities in order to change incorrect data.

**Acceptance Criteria**
- Add heading to the current page 
- In the 'view entity' dialog there should be an edit button in the appbar that opens an edit dialog
- For each property in the model there should be an input field with the current value of the model
- When the user presses OK then the data is sent to the server
- In case of an error the user stays at the update dialog
- In case of success the user is taken to the show entity dialog

**Comment by TugbaDalmaz** [comment]
[https://app.zenhub.com/workspaces/strategic-roadmap-618109f00a16a50018a8acb2/issues/devonfw-forge/devon4flutter-non-bloc-arch/10](show employee dialog) is included in this issue

**Comment by TugbaDalmaz** [comment]
@nico this ticket would be removed and continued in **"modify the state management of the employee dialog"**
