### ISSUE TITLE
Load data from backend

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw-forge/devon4flutter-non-bloc-arch#7]
**Description**
As a user I would like my app to load the data from the server/mock in order to be able to have no static data in the app.

**Acceptance Criteria**
- The data that is in the BLOC Repository is loaded from the configured API/Mock on startup

**Comment by martellux** [comment]
I suppose/suggest you can use the same data model of the previous backend.
If you look at the data model of the previous Flutter app, in this [folder](https://github.com/devonfw-sample/flutter-employee-app/tree/master/lib/model/network), you can figure out the JSON structure for each request and response that the backend exposes.
In this way, it should be easy for you to migrate from the mock version to the real one when the backend will be working again.
